name: Tests

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches: [main]
  pull_request:
    types: [
        synchronize, # PR was updated
        opened, # PR was open
        reopened, # PR was closed and is now open again
        ready_for_review, # PR was converted from draft to open
      ]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ env.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install Dependencies
        run: npm ci --legacy-peer-deps

      - name: Run Unit Tests and generate coverage
        run: npm run test:coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ env.GITHUB_TOKEN }}

      - name: Run Mutation Tests
        if: github.event_name == 'pull_request'
        run: npm run test:mutation

      - name: Run Mutation Tests and publish reports
        if: github.event_name != 'pull_request'
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
        run: npm run test:mutation-report

      - name: Run Unit Test in dist
        run: |
          npm pack
          tar zxvf *.tgz
          npm run test:bundle
